import { Octokit } from "@octokit/rest";
import dotenv from "dotenv";

import type { GeneratedPRRunbook, GeneratedRunbook } from "./aiEngine.js";

dotenv.config();

const octokit = new Octokit({
    auth: process.env.GITHUB_TOKEN
});

const OWNER = process.env.GITHUB_OWNER || "";
const REPO = process.env.GITHUB_REPO || "";

if (!process.env.GITHUB_TOKEN || !OWNER || !REPO) {
    throw new Error("Missing required environment variables: GITHUB_TOKEN, GITHUB_OWNER, and GITHUB_REPO must be set");
}

const toFileName = (title: string): string => {
    const sanitized = title
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .trim();

    if (!sanitized) {
        throw new Error("Cannot generate filename from empty title");
    }

    return sanitized + ".md";
};

const toMarkdown = (runbook: GeneratedRunbook | GeneratedPRRunbook, approvedBy: string): string => {
    const date = new Date().toLocaleDateString("en-GB", {
        day: "numeric",
        month: "long",
        year: "numeric"
    });

    const severityEmoji = {
        high: "🔴",
        medium: "🟡",
        low: "🟢"
    }[runbook.severity?.toLowerCase()] || "⚪";

    const formatList = (items: string[] = []) =>
        items.map(item => `- ${item}`).join("\n") || "- Not specified";

    return `# ${runbook.title}

> ${severityEmoji} **Severity:** ${runbook.severity?.toUpperCase() || "UNKNOWN"} | **Date:** ${date} | **Owner:** ${runbook.owner || "Unknown"}

---

## 📋 Overview
${runbook.overview || "No overview available"}

---

## 🔍 Key Events
${formatList(runbook.keyEvents)}

---

## 🔑 Root Cause
${runbook.rootCause || "Not specified"}

---

## 🛠️ Actions Taken
${formatList(runbook.actionsTaken)}

---

## 🛡️ Prevention Steps
${formatList(runbook.preventionSteps)}

---

## 📅 Incident Timeline

| Field | Value |
|---|---|
| Started | ${runbook.incidentStart || "Unknown"} |
| Ended | ${runbook.incidentEnd || "Unknown"} |
| Owner | ${runbook.owner || "Unknown"} |
| Approved By | ${approvedBy} |
| Documented | ${date} |

---

*This runbook was automatically generated by RunbookAI*
`;
};


export const publishToGitHub = async (
    runbook: GeneratedRunbook | GeneratedPRRunbook,
    approvedBy: string,
    repoOwner: string,
    repoName: string
): Promise<string> => {
    console.log("🐙 Publishing to GitHub...");

    const fileName = toFileName(runbook.title);
    const filePath = `docs/runbooks/${fileName}`;
    const content = toMarkdown(runbook, approvedBy);
    const encodedContent = Buffer.from(content).toString("base64");

    try {
        let existingFileSha: string | undefined;

        try {
            const { data } = await octokit.repos.getContent({
                owner: repoOwner,
                repo: repoName,
                path: filePath
            });
            if ("sha" in data) {
                existingFileSha = data.sha;
            }
        } catch (error: any) {
            if (error.status !== 404) throw error;
        }

        const { data } = await octokit.repos.createOrUpdateFileContents({
            owner: repoOwner,
            repo: repoName,
            path: filePath,
            message: existingFileSha
                ? `docs: update runbook "${runbook.title}"`
                : `docs: add runbook "${runbook.title}"`,
            content: encodedContent,
            ...(existingFileSha ? { sha: existingFileSha } : {})
        });

        const fileUrl = `https://github.com/${repoOwner}/${repoName}/blob/main/${filePath}`;
        console.log(`Published to GitHub: ${fileUrl}`);
        return fileUrl;

    } catch (error: any) {
        console.error("GitHub publish error:", error.message);
        throw error;
    }
};


export const postRunbookComment = async (
    prNumber: number,
    runbook: GeneratedPRRunbook,
    repoOwner: string,
    repoName: string
): Promise<number> => {
    console.log(`💬 Posting runbook comment on PR #${prNumber}...`);

    const severityEmoji = {
        high: "🔴",
        medium: "🟡",
        low: "🟢"
    }[runbook.severity?.toLowerCase()] || "⚪";

    const formatList = (items: string[] = []) =>
        items.map((item, i) => `${i + 1}. ${item}`).join("\n") || "Not specified";

    // Embed runbook data as hidden HTML comment
    const hiddenData = `<!--RUNBOOK_DATA:${JSON.stringify(runbook)}-->`;

    const commentBody = `## 🤖 RunbookAI — Runbook Draft

A runbook has been automatically generated from this PR.

---

### ${severityEmoji} ${runbook.title}

**Severity:** ${runbook.severity?.toUpperCase() || "UNKNOWN"}

**Overview:**
${runbook.overview || "No overview"}

**Root Cause:**
${runbook.rootCause || "Not specified"}

**Actions Taken:**
${formatList(runbook.actionsTaken)}

**Prevention Steps:**
${formatList(runbook.preventionSteps)}

---

### ✅ To approve: reply \`approve\`
### ❌ To reject: reply \`reject\`

${hiddenData}`;

    const { data } = await octokit.issues.createComment({
        owner: repoOwner,
        repo: repoName,
        issue_number: prNumber,
        body: commentBody
    });

    console.log(`✅ Comment posted — ID: ${data.id}`);
    return data.id;
};


export const deleteComment = async (
    commentId: number,
    repoOwner: string,
    repoName: string
): Promise<void> => {
    try {
        await octokit.issues.deleteComment({
            owner: repoOwner,
            repo: repoName,
            comment_id: commentId
        });
        console.log(`🗑️ Deleted approval comment ${commentId}`);
    } catch (error) {
        console.error("Error deleting comment:", error);
    }
};


export const postStatusComment = async (
    prNumber: number,
    status: "approved" | "rejected",
    runbookTitle: string,
    githubUrl: string | null,
    repoOwner: string,
    repoName: string
): Promise<void> => {
    const body = status === "approved"
        ? `✅ **RunbookAI — Runbook Approved**\n\nRunbook "*${runbookTitle}*" has been saved.\n\n📄 [View Runbook](${githubUrl})`
        : `❌ **RunbookAI — Runbook Rejected**\n\nRunbook "*${runbookTitle}*" was discarded.`;

    await octokit.issues.createComment({
        owner: repoOwner,
        repo: repoName,
        issue_number: prNumber,
        body
    });
};