import { Octokit } from "@octokit/rest";
import dotenv from "dotenv";

import type { GeneratedPRRunbook } from "./aiEngine.js";

dotenv.config();

let _octokit: Octokit | null = null;

/**
 * Lazy GitHub client. Throws only when a GitHub operation is actually
 * attempted without GITHUB_TOKEN — importing this module never crashes
 * the server (Slack-only dev boots fine).
 */
function getOctokit(): Octokit {
    if (!_octokit) {
        const token = process.env.GITHUB_TOKEN;
        if (!token) {
            throw new Error("GITHUB_TOKEN is not set — GitHub operations are disabled");
        }
        _octokit = new Octokit({ auth: token });
    }
    return _octokit;
}

/** True when GitHub operations are available (token present). */
export function isGitHubEnabled(): boolean {
    return Boolean(process.env.GITHUB_TOKEN);
}
const toFileName = (title: string): string => {
    const sanitized = title
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .trim();

    if (!sanitized) {
        throw new Error("Cannot generate filename from empty title");
    }

    return sanitized + ".md";
};

const toMarkdown = (runbook: GeneratedPRRunbook, approvedBy: string): string => {
    const date = new Date().toLocaleDateString("en-GB", {
        day: "numeric",
        month: "long",
        year: "numeric"
    });

    const severityEmoji = {
        high: "🔴",
        medium: "🟡",
        low: "🟢"
    }[runbook.severity?.toLowerCase()] || "⚪";

    const formatList = (items: string[] = []) =>
        items.map(item => `- ${item}`).join("\n") || "- Not specified";

    return `# ${runbook.title}

> ${severityEmoji} **Severity:** ${runbook.severity?.toUpperCase() || "UNKNOWN"} | **Date:** ${date} | **Owner:** ${runbook.owner || "Unknown"}

---

## 📋 Overview
${runbook.overview || "No overview available"}

---

## 🔍 Key Events
${formatList(runbook.keyEvents)}

---

## 🔑 Root Cause
${runbook.rootCause || "Not specified"}

---

## 🛠️ Actions Taken
${formatList(runbook.actionsTaken)}

---

## 🛡️ Prevention Steps
${formatList(runbook.preventionSteps)}

---

## 📅 Incident Timeline

| Field | Value |
|---|---|
| Started | ${runbook.incidentStart || "Unknown"} |
| Ended | ${runbook.incidentEnd || "Unknown"} |
| Owner | ${runbook.owner || "Unknown"} |
| Approved By | ${approvedBy} |
| Documented | ${date} |

---

*This runbook was automatically generated by RunbookAI*
`;
};


export const publishToGitHub = async (
    runbook: GeneratedPRRunbook,
    approvedBy: string,
    repoOwner: string,
    repoName: string
): Promise<string> => {
    console.log("🐙 Publishing to GitHub...");

    const fileName = toFileName(runbook.title);
    const filePath = `docs/runbooks/${fileName}`;
    const content = toMarkdown(runbook, approvedBy);
    const encodedContent = Buffer.from(content).toString("base64");

    try {
        let existingFileSha: string | undefined;

        try {
            const { data } = await getOctokit().repos.getContent({
                owner: repoOwner,
                repo: repoName,
                path: filePath
            });
            if ("sha" in data) {
                existingFileSha = data.sha;
            }
        } catch (error: any) {
            if (error.status !== 404) throw error;
        }

        const { data } = await getOctokit().repos.createOrUpdateFileContents({
            owner: repoOwner,
            repo: repoName,
            path: filePath,
            message: existingFileSha
                ? `docs: update runbook "${runbook.title}"`
                : `docs: add runbook "${runbook.title}"`,
            content: encodedContent,
            ...(existingFileSha ? { sha: existingFileSha } : {})
        });

        const { data: repoData } = await getOctokit().repos.get({ owner: repoOwner, repo: repoName });
        const defaultBranch = repoData.default_branch || "main";

        const fileUrl = `https://github.com/${repoOwner}/${repoName}/blob/${defaultBranch}/${filePath}`;
        console.log(`Published to GitHub: ${fileUrl}`);
        return fileUrl;

    } catch (error: any) {
        console.error("GitHub publish error:", error.message);
        throw error;
    }
};


export const postRunbookComment = async (
    prNumber: number,
    runbook: GeneratedPRRunbook,
    repoOwner: string,
    repoName: string
): Promise<number> => {
    console.log(`💬 Posting runbook comment on PR #${prNumber}...`);

    const severityEmoji = {
        high: "🔴",
        medium: "🟡",
        low: "🟢"
    }[runbook.severity?.toLowerCase()] || "⚪";

    const formatList = (items: string[] = []) =>
        items.map((item, i) => `${i + 1}. ${item}`).join("\n") || "Not specified";

    const hiddenData = `<!--RUNBOOK_DATA:${JSON.stringify(runbook)}-->`;

    const commentBody = `## 🤖 RunbookAI — Runbook Draft

A runbook has been automatically generated from this PR.

---

### ${severityEmoji} ${runbook.title}

**Severity:** ${runbook.severity?.toUpperCase() || "UNKNOWN"}

**Overview:**
${runbook.overview || "No overview"}

**Root Cause:**
${runbook.rootCause || "Not specified"}

**Actions Taken:**
${formatList(runbook.actionsTaken)}

**Prevention Steps:**
${formatList(runbook.preventionSteps)}

---

### ✅ To approve: reply \`approve\`
### ❌ To reject: reply \`reject\`

${hiddenData}`;

    const { data } = await getOctokit().issues.createComment({
        owner: repoOwner,
        repo: repoName,
        issue_number: prNumber,
        body: commentBody
    });

    console.log(`✅ Comment posted — ID: ${data.id}`);
    return data.id;
};


export const deleteComment = async (
    commentId: number,
    repoOwner: string,
    repoName: string
): Promise<void> => {
    try {
        await getOctokit().issues.deleteComment({
            owner: repoOwner,
            repo: repoName,
            comment_id: commentId
        });
        console.log(`🗑️ Deleted approval comment ${commentId}`);
    } catch (error) {
        console.error("Error deleting comment:", error);
    }
};


export const postStatusComment = async (
    prNumber: number,
    status: "approved" | "rejected",
    runbookTitle: string,
    githubUrl: string | null,
    repoOwner: string,
    repoName: string
): Promise<void> => {
    const body = status === "approved"
        ? `✅ **RunbookAI — Runbook Approved**\n\nRunbook "*${runbookTitle}*" has been saved.\n\n📄 [View Runbook](${githubUrl})`
        : `❌ **RunbookAI — Runbook Rejected**\n\nRunbook "*${runbookTitle}*" was discarded.`;

    await getOctokit().issues.createComment({
        owner: repoOwner,
        repo: repoName,
        issue_number: prNumber,
        body
    });
};
